# Generated by Django 4.2.1 on 2023-05-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commissions_Other_Bank',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cheques', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommissionsBank_USF',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('amount_max', models.IntegerField(null=True)),
                ('amount_min', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Name_Bank',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_bank', models.CharField(max_length=50)),
            ],
        ),
    ]
