# Generated by Django 4.2.1 on 2023-05-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionsbank_usf',
            name='type',
            field=models.CharField(choices=[('$', 'PESOS'), ('US$', 'DÓLARES'), ('%', 'PORCENTAJE')], default='PESOS', max_length=50),
        ),
        migrations.AlterField(
            model_name='commissionsbank_usf',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
