# Generated by Django 4.2.1 on 2023-05-26 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commissionsbank_usf_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionsbank_usf',
            name='amount_max',
        ),
        migrations.RemoveField(
            model_name='commissionsbank_usf',
            name='amount_min',
        ),
    ]
