# Generated by Django 4.2.1 on 2023-05-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_remove_commissionsbank_usf_amount_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commissions_OtherBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('$', 'PESOS'), ('US$', 'DÓLARES'), ('%', 'PORCENTAJE')], default='PESOS', max_length=50)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Commissions_Other_Bank',
        ),
        migrations.DeleteModel(
            name='Name_Bank',
        ),
    ]
