# Generated by Django 4.2.1 on 2023-05-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_commissions_otherbank_delete_commissions_other_bank_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commissions_OtherBank',
        ),
    ]
