# Generated by Django 4.2.1 on 2023-05-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_delete_commissions_otherbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionsbank_usf',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
