# Generated by Django 4.2.1 on 2023-05-27 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_alter_commissionsbank_usf_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount_CommissionsBank_USF',
            fields=[
                ('name_client', models.CharField(max_length=50)),
                ('percent_discount', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Identification_Commissions_Bank_USF',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Input_CommissionsBank_USF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employee', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('$', 'PESOS'), ('US$', 'DÓLARES'), ('%', 'PORCENTAJE')], default='PESOS', max_length=50)),
                ('amount', models.FloatField(null=True)),
                ('id_commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.identification_commissions_bank_usf')),
            ],
        ),
        migrations.DeleteModel(
            name='CommissionsBank_USF',
        ),
        migrations.AddField(
            model_name='discount_commissionsbank_usf',
            name='id_commission_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commissions.identification_commissions_bank_usf'),
        ),
    ]
