# Generated by Django 4.2.1 on 2023-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0007_discount_commissionsbank_usf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input_commissionsbank_usf',
            name='id',
        ),
        migrations.AlterField(
            model_name='discount_commissionsbank_usf',
            name='id_commission_discount',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discount_commissionsbank_usf',
            name='percent_discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='input_commissionsbank_usf',
            name='id_commission',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
