# Generated by Django 4.2.1 on 2023-06-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0008_remove_input_commissionsbank_usf_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_commissionsbank_usf',
            name='type',
            field=models.CharField(choices=[('$', 'PESOS'), ('US$', 'DÓLARES')], default='PESOS', max_length=50),
        ),
    ]
