# Generated by Django 4.2.1 on 2023-05-26 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name_Bank',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commissions_OthersBanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('$', 'PESOS'), ('US$', 'DÓLARES'), ('%', 'PORCENTAJE')], default='PESOS', max_length=50)),
                ('amount', models.IntegerField(null=True)),
                ('id_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='othersbanks.name_bank')),
            ],
        ),
    ]
